name: Bug Report
description: Create a bug report for the Camelot library.
title: "[BUG]: "
labels: ["fix", "needs-triage"]
body:
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Provide the C code or Makefile command that triggers the failure.
      placeholder: |
        1. create arena...
        2. push to list...
        3. segfault.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Compiler version, and Architecture.
      placeholder: "Ubuntu 24.04 / GCC 13.3 / x86_64"
    validations:
      required: true