name: Feature Request
description: Suggest an architectural change or new utility.
title: "[RFC]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Technical Constraint Check:**
        Features must align with the "Zero Allocation" and "Arena-First" philosophy.
  - type: textarea
    id: pitch
    attributes:
      label: The Problem
      description: What engineering friction are you trying to solve?
      placeholder: "I find myself rewriting string trimming logic in every project..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the API or implementation.
      placeholder: "Implement string.trim() using pointer arithmetic (non-destructive)."
    validations:
      required: true