name: Roadmap Directive
description: (Restricted) Strategic roadmap items for Steering Committee.
title: "[PLAN]: "
labels: ["roadmap", "priority-high"]
assignees: ["(your-username)"] 
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ RESTRICTED ACCESS
        **This template is for the Steering Committee only.** Community members: Please use "Feature Request" to suggest changes.
  - type: textarea
    id: directive
    attributes:
      label: Directive / Specification
      description: Define the architectural requirement and technical constraints.
      placeholder: "Implement X using Y pattern. Must not allocate memory."
    validations:
      required: true